### ISSUE TITLE
Exception thrown when REST server is down

### ISSUE THREAD

**Issue by farhan3** [IBM-Bluemix/gp-python-client#1]
When the REST server is down, the following message is displayed by Bluemix: 
`"404 Not Found: Requested route ('<url>') does not exist."`

This causes parsing issue:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/farhan/workspaces/tmp/2016-01-21-1453415273/lib/python2.7/site-packages/gpclient/gpclient.py", line 415, in translation
    availableLangs = self.get_avaliable_languages(bundleId)
  File "/home/farhan/workspaces/tmp/2016-01-21-1453415273/lib/python2.7/site-packages/gpclient/gpclient.py", line 365, in get_avaliable_languages
    bundleData = self.__get_bundle_data(bundleId)
  File "/home/farhan/workspaces/tmp/2016-01-21-1453415273/lib/python2.7/site-packages/gpclient/gpclient.py", line 282, in __get_bundle_data
    response = self.__perform_rest_get_call(requestURL=url)
  File "/home/farhan/workspaces/tmp/2016-01-21-1453415273/lib/python2.7/site-packages/gpclient/gpclient.py", line 244, in __perform_rest_get_call
    jsonR = r.json()
  File "/home/farhan/workspaces/tmp/2016-01-21-1453415273/lib/python2.7/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 104)

```

**Comment by srl295** [comment]
Looks like we already check the status code:

```
    logging.info('HTTP status code: %s', httpStatus)
```

… just need to verify it == 200 before continuing.
